# Generated by Django 4.0 on 2021-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='item',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='item',
            field=models.ManyToManyField(to='inventoryapp.Item'),
        ),
    ]
