# Generated by Django 4.0 on 2021-12-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepurchaseitem',
            old_name='cus_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='cus_id',
            new_name='customer',
        ),
    ]
