# Generated by Django 4.0 on 2021-12-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_rename_cus_id_invoicepurchaseitem_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepurchaseitem',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
    ]
