# Generated by Django 4.0 on 2021-12-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_remove_purchaseitem_item_purchaseitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
    ]
